
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author monasterio.hodei
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        textzenbakitzailea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textizendatzailea = new javax.swing.JTextField();
        buttonsinplifikatu = new javax.swing.JButton();
        texterantzunazenbakitzailea = new javax.swing.JLabel();
        texterantzunaizendatzailea = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texthamartarbaliokidea = new javax.swing.JLabel();
        texterantzunahamartar = new javax.swing.JLabel();
        buttonreseteatu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 51, 102));
        labelTitulo.setText("Zatikien Sinplifikazioa:");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 470, 70));

        textzenbakitzailea.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        textzenbakitzailea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textzenbakitzailea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textzenbakitzaileaActionPerformed(evt);
            }
        });
        getContentPane().add(textzenbakitzailea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 80, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("_______");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 80));

        textizendatzailea.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        textizendatzailea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(textizendatzailea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 60));

        buttonsinplifikatu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonsinplifikatu.setText("sinplifikatu=");
        buttonsinplifikatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsinplifikatuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonsinplifikatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 160, -1));

        texterantzunazenbakitzailea.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        texterantzunazenbakitzailea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texterantzunazenbakitzailea, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 50));

        texterantzunaizendatzailea.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        texterantzunaizendatzailea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texterantzunaizendatzailea, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 80, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("______");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, 40));

        texthamartarbaliokidea.setVisible(false);
        texthamartarbaliokidea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        texthamartarbaliokidea.setText("Balio hamartarra=");
        getContentPane().add(texthamartarbaliokidea, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 210, -1));

        texterantzunahamartar.setVisible(false);
        texterantzunahamartar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(texterantzunahamartar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 100, 50));

        buttonreseteatu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonreseteatu.setText("Reseteatu");
        buttonreseteatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonreseteatuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonreseteatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 340, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textzenbakitzaileaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textzenbakitzaileaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textzenbakitzaileaActionPerformed

    private void buttonsinplifikatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsinplifikatuActionPerformed
     int zenbakitzailea=Integer.parseInt(textzenbakitzailea.getText());
     int izendatzailea=Integer.parseInt(textizendatzailea.getText());
        Zatikia zat1= new Zatikia(zenbakitzailea,izendatzailea);
        Zatikia zat2= new Zatikia(zenbakitzailea,izendatzailea);
        zat1.sinplifikatu();
        if(zat1.getZenbakitzailea()== zat2.getZenbakitzailea()&& zat1.getIzendatzailea()== zat2.getIzendatzailea()){
            JOptionPane.showMessageDialog(null, "Ezin daiteke gehiago sinplifikatu.", "Errorea", JOptionPane.ERROR_MESSAGE);
            
        }
        
        texterantzunazenbakitzailea.setText(String.valueOf(zat1.getZenbakitzailea()));
        texterantzunaizendatzailea.setText(String.valueOf(zat1.getIzendatzailea()));
        int confirm= showConfirmDialog(null, "Zatikiaren balio hamartarra jakin nahi duzu?");
        if(confirm==0){
            texterantzunahamartar.setVisible(true);
            texthamartarbaliokidea.setVisible(true);
            texterantzunahamartar.setText(String.valueOf(zat2.hamartarBaliokidea()));
        
        }
        
        
    }//GEN-LAST:event_buttonsinplifikatuActionPerformed

    private void buttonreseteatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonreseteatuActionPerformed
       textzenbakitzailea.setText("");
        textizendatzailea.setText("");
        texterantzunazenbakitzailea.setText("");
        texterantzunaizendatzailea.setText("");
        texterantzunahamartar.setVisible(false);
            texthamartarbaliokidea.setVisible(false);
    }//GEN-LAST:event_buttonreseteatuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonreseteatu;
    private javax.swing.JButton buttonsinplifikatu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel texterantzunahamartar;
    private javax.swing.JLabel texterantzunaizendatzailea;
    private javax.swing.JLabel texterantzunazenbakitzailea;
    private javax.swing.JLabel texthamartarbaliokidea;
    private javax.swing.JTextField textizendatzailea;
    private javax.swing.JTextField textzenbakitzailea;
    // End of variables declaration//GEN-END:variables
}
